import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "path";
import { writeFileSync, mkdirSync } from "fs";
import runtimeErrorOverlay from "@replit/vite-plugin-runtime-error-modal";
import { VitePWA } from "vite-plugin-pwa";

// ── Build target detection ─────────────────────────────────────────────────
// CAP_ANDROID=1 → Capacitor/Android build: use base './' so that
// file:///android_asset/public/... paths resolve correctly in the WebView.
// Web builds keep the usual absolute base path for proxy routing.
const isAndroidBuild = process.env.CAP_ANDROID === "1";

const rawPort = process.env.PORT;
if (!isAndroidBuild && !rawPort) throw new Error("PORT environment variable is required but was not provided.");
const port = rawPort ? Number(rawPort) : 3000;
if (!isAndroidBuild && (Number.isNaN(port) || port <= 0)) throw new Error(`Invalid PORT value: "${rawPort}"`);

const basePath = process.env.BASE_PATH ?? "/arc-guard/";
if (!isAndroidBuild && !process.env.BASE_PATH) throw new Error("BASE_PATH environment variable is required but was not provided.");

// Android WebView file:// origin — relative base is required.
const effectiveBase = isAndroidBuild ? "./" : basePath;

const isProd = process.env.NODE_ENV === "production";

// ── Inject Replit Secrets into browser bundle ──────────────────────────────
// Vite in dev mode gives its own import.meta.env handling priority over
// the define block, so we use a custom global __ARC_GUARD_CONFIG__ that
// Vite has no special handling for — guaranteed to reach the browser.
const g = (k: string) => process.env[k] ?? "";
const arcGuardConfig = {
  apiKey:            g("VITE_ARC_GUARD_API_KEY"),
  authDomain:        g("VITE_ARC_GUARD_AUTH_DOMAIN"),
  projectId:         g("VITE_ARC_GUARD_PROJECT_ID"),
  storageBucket:     g("VITE_ARC_GUARD_STORAGE_BUCKET"),
  messagingSenderId: g("VITE_ARC_GUARD_MESSAGING_SENDER_ID"),
  appId:             g("VITE_ARC_GUARD_APP_ID"),
  measurementId:     g("VITE_ARC_GUARD_MEASUREMENT_ID"),
  vapidKey:          g("VITE_ARC_GUARD_VAPID_KEY"),
};
// Debug log (no secret values are printed — only presence)
for (const [k, v] of Object.entries(arcGuardConfig)) {
  console.log(`[arc-guard env] ${k}: ${v ? "✓ set" : "✗ missing"}`);
}
const envDefine = {
  __ARC_GUARD_CONFIG__: JSON.stringify(arcGuardConfig),
  // Baked-in at build time via CI env var APP_FLAVOR.
  // "manager" → Manager APK auto-navigates to /manager on launch.
  // "guard"   → Guard APK auto-navigates to /guard on launch.
  // ""        → web build / unspecified — LandingPage shows the chooser.
  __APP_FLAVOR__: JSON.stringify(process.env.APP_FLAVOR ?? ""),
};

// ── Firebase Messaging Service Worker generator ────────────────────────────
// Generates /arc-guard/firebase-messaging-sw.js with Firebase config injected.
// Uses the CDN compat SDK (importScripts) to avoid ESM issues in SW context.
function generateFcmSwContent(cfg: typeof arcGuardConfig): string {
  const fcfg = JSON.stringify({
    apiKey:            cfg.apiKey,
    authDomain:        cfg.authDomain,
    projectId:         cfg.projectId,
    storageBucket:     cfg.storageBucket,
    messagingSenderId: cfg.messagingSenderId,
    appId:             cfg.appId,
  }, null, 2);
  return `// ARC Guard — Firebase Cloud Messaging Service Worker
// Auto-generated by vite.config.ts — DO NOT EDIT MANUALLY
// Handles FCM background push messages when the manager app is closed/backgrounded.

importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js');

var firebaseConfig = ${fcfg};

if (firebaseConfig.apiKey) {
  try {
    firebase.initializeApp(firebaseConfig);
    var messaging = firebase.messaging();

    // ── Background message handler ────────────────────────────────────────────
    // Fires when an FCM push arrives while the tab is not focused (backgrounded/closed).
    messaging.onBackgroundMessage(function(payload) {
      var n    = payload.notification || {};
      var data = payload.data         || {};
      var kind = data.kind            || '';

      var title = n.title || (
        kind === 'sos'     ? 'ARC Guard 🚨 SOS اضطراری'    :
        kind === 'outside' ? 'ARC Guard ⚠️ خارج از محدوده' :
        kind === 'missed'  ? 'ARC Guard ⏰ ایستگاه از دست رفت' :
                             'ARC Guard 🔔 هشدار جدید'
      );

      self.registration.showNotification(title, {
        body:               n.body || (data.guardName ? data.guardName + (data.checkpointName ? ' · ' + data.checkpointName : '') : 'هشدار جدید دریافت شد'),
        icon:               n.icon || '/arc-guard/icon-192.png',
        badge:              '/arc-guard/icon-96.png',
        tag:                'arc-guard-' + (data.alertId || Date.now()),
        requireInteraction: kind === 'sos',
        dir:                'rtl',
        data:               data,
        vibrate:            kind === 'sos' ? [300,100,300,100,300,100,500] : [200,100,200],
      });
    });

    console.log('[ARC Guard FCM-SW] Firebase Messaging initialized');
  } catch(err) {
    console.error('[ARC Guard FCM-SW] init failed:', err);
  }
} else {
  console.warn('[ARC Guard FCM-SW] Firebase config missing — push notifications disabled');
}

// ── Notification click → open/focus manager alerts tab ───────────────────────
self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  var alertsUrl = '/arc-guard/?tab=alerts';
  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then(function(clients) {
        for (var i = 0; i < clients.length; i++) {
          var client = clients[i];
          if (client.url.includes('/arc-guard/') && 'focus' in client) {
            client.focus();
            client.postMessage({ type: 'NAVIGATE_TO_ALERTS' });
            return;
          }
        }
        if (self.clients.openWindow) {
          return self.clients.openWindow(alertsUrl);
        }
      })
  );
});
`;
}

export default defineConfig({
  base: effectiveBase,
  plugins: [
    react(),
    tailwindcss(),
    runtimeErrorOverlay(),

    // ── Plugin: emit firebase-messaging-sw.js with injected config ────────────
    {
      name: "arc-guard-fcm-sw",

      // Dev: serve the generated SW at the expected path
      configureServer(server) {
        const content = generateFcmSwContent(arcGuardConfig);
        server.middlewares.use(
          "/arc-guard/firebase-messaging-sw.js",
          (_req, res) => {
            res.setHeader("Content-Type", "application/javascript; charset=utf-8");
            res.setHeader("Service-Worker-Allowed", "/arc-guard/");
            res.end(content);
          },
        );
      },

      // Build: write the file into dist/public/ alongside the built assets
      closeBundle() {
        const content = generateFcmSwContent(arcGuardConfig);
        const outDir  = path.resolve(import.meta.dirname, "dist/public");
        try { mkdirSync(outDir, { recursive: true }); } catch { /* exists */ }
        writeFileSync(path.join(outDir, "firebase-messaging-sw.js"), content, "utf-8");
        console.log("[arc-guard-fcm-sw] firebase-messaging-sw.js written to dist/public/");
      },
    },

    // ── PWA / Service Worker ────────────────────────────────────────────────
    // Skip entirely for Android (Capacitor) builds.
    // Inside Capacitor the app runs at http://localhost with no /arc-guard/
    // prefix, so the SW scope and manifest URLs built for the web don't match.
    // The registerSW() call from virtual:pwa-register can also interfere with
    // WebView startup on some Android versions.
    // A no-op shim for virtual:pwa-register is injected below so that
    // pwa.ts compiles successfully without the real VitePWA plugin.
    ...(!isAndroidBuild ? [VitePWA({
      registerType: "prompt",
      injectRegister: false,
      strategies: "injectManifest",
      srcDir: "src",
      filename: "sw.ts",
      injectManifest: {
        injectionPoint: "self.__WB_MANIFEST",
        globPatterns: ["**/*.{js,css,html,ico,png,svg,woff2}"],
        globIgnores: ["**/*logo*", "**/*-logo*"],
        maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
      },
      devOptions: { enabled: false },

      manifest: {
        name: "ARC Guard v4.0 — سیستم گشت امنیتی",
        short_name: "ARC Guard",
        description: "سیستم هوشمند گشت و نگهبانی با QR Code و GPS — پلتفرم SaaS امنیتی",
        theme_color: "#0c1829",
        background_color: "#0c1829",
        display: "standalone",
        display_override: ["window-controls-overlay", "standalone", "minimal-ui"],
        orientation: "portrait-primary",
        scope: basePath,
        start_url: basePath + "?source=pwa",
        id: basePath,
        lang: "fa",
        dir: "rtl",
        categories: ["security", "business", "productivity"],
        prefer_related_applications: false,
        icons: [
          { src: "icon-72.png",          sizes: "72x72",   type: "image/png" },
          { src: "icon-96.png",          sizes: "96x96",   type: "image/png" },
          { src: "icon-128.png",         sizes: "128x128", type: "image/png" },
          { src: "icon-144.png",         sizes: "144x144", type: "image/png" },
          { src: "icon-152.png",         sizes: "152x152", type: "image/png" },
          { src: "icon-192.png",         sizes: "192x192", type: "image/png" },
          { src: "icon-384.png",         sizes: "384x384", type: "image/png" },
          { src: "icon-512.png",         sizes: "512x512", type: "image/png" },
          { src: "icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
        shortcuts: [
          {
            name: "داشبورد مدیر",
            short_name: "داشبورد",
            description: "ورود به داشبورد مدیریت و مانیتور نگهبانان",
            url: basePath + "?role=manager",
            icons: [{ src: "icon-96.png", sizes: "96x96" }],
          },
          {
            name: "شروع گشت",
            short_name: "گشت",
            description: "ورود نگهبان و شروع گشت امنیتی",
            url: basePath + "?role=guard",
            icons: [{ src: "icon-96.png", sizes: "96x96" }],
          },
        ],
        screenshots: [
          {
            src: "icon-512.png",
            sizes: "512x512",
            type: "image/png",
            form_factor: "narrow",
            label: "ARC Guard داشبورد امنیتی",
          },
        ],
        related_applications: [
          {
            platform: "play",
            url: "https://play.google.com/store/apps/details?id=com.arcguard.security",
            id: "com.arcguard.security",
          },
        ],
      },
    })] : []),

    // ── Android build: no-op shim for virtual:pwa-register ─────────────────
    // pwa.ts imports registerSW from virtual:pwa-register which is provided
    // by vite-plugin-pwa. When VitePWA is skipped (isAndroidBuild), we inject
    // a tiny no-op so the import resolves and pwa.ts compiles without errors.
    ...(isAndroidBuild ? [{
      name: "arc-guard-nop-pwa-register",
      resolveId(id: string) {
        if (id === "virtual:pwa-register") return "\0virtual:pwa-register-nop";
      },
      load(id: string) {
        if (id === "\0virtual:pwa-register-nop")
          return "export const registerSW = () => () => {};";
      },
    }] : []),

    ...(process.env.NODE_ENV !== "production" && process.env.REPL_ID !== undefined
      ? [
          await import("@replit/vite-plugin-cartographer").then((m) =>
            m.cartographer({ root: path.resolve(import.meta.dirname, "..") }),
          ),
          await import("@replit/vite-plugin-dev-banner").then((m) => m.devBanner()),
        ]
      : []),
  ],

  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "src"),
      "@assets": path.resolve(import.meta.dirname, "..", "..", "attached_assets"),
    },
    dedupe: ["react", "react-dom"],
  },

  root: path.resolve(import.meta.dirname),

  build: {
    outDir: path.resolve(import.meta.dirname, "dist/public"),
    emptyOutDir: true,
    // Android WebView ~Chromium 89+; web targets modern evergreen browsers
    target: isAndroidBuild ? "es2020" : "esnext",
    // Source maps in production for error tracking
    sourcemap: isProd ? "hidden" : true,
    // Warn on chunks > 600 KB (before gzip)
    chunkSizeWarningLimit: 600,
    rollupOptions: {
      output: {
        // Split vendor bundles so users only re-download what changed
        manualChunks: {
          // React core (rarely changes)
          "vendor-react": ["react", "react-dom"],
          // Firebase — split auth vs firestore (guards need both, but loaded async)
          "vendor-firebase": ["firebase/app", "firebase/auth", "firebase/firestore"],
          // QR scanner — only loaded when scanning (dynamic import in GuardPatrol)
          // Note: html5-qrcode is already dynamically imported via import()
          // Maps
          "vendor-maps": ["leaflet"],
          // Charts + UI
          "vendor-ui": ["@tanstack/react-query", "lucide-react"],
        },
      },
    },
  },

  define: envDefine,

  server: {
    port,
    strictPort: true,
    host: "0.0.0.0",
    allowedHosts: true,
    fs: { strict: true },
  },

  preview: {
    port,
    host: "0.0.0.0",
    allowedHosts: true,
  },
});
